TOPICS = [
    "Tech Innovation",
    "Global Markets",
    "Environmental Policy",
    "Public Health",
    "Urban Development",
    "International Relations",
    "Education Reform",
    "Cultural Trends",
    "Scientific Discoveries",
    "Economic Policy",
    "Sports Industry",
    "Media & Entertainment",
    "Workplace Transformation",
    "Transportation & Mobility",
    "Food & Agriculture",
    "Medical & Healthcare",
    "Legal & Compliance",
    "E-commerce & Retail",
    "Financial Services",
    "Gaming & Software",
    "Marketing & Advertising",
    "Government Documentation",
    "Academic Research",
    "Patents & Intellectual Property",
    "Manufacturing & Safety",
    "Tourism & Hospitality",
    "Religious & Cultural Studies",
    "Insurance & Risk Management",
    "Consumer Electronics",
    "Pharmaceutical Industry",
    "Fashion & Apparel",
    "Beauty & Cosmetics",
    "Home & Living",
    "Automotive Industry",
    "Social Media",
    "Dating & Relationships",
    "Parenting & Family",
    "Arts & Culture",
    "Music Industry",
    "Film & Cinema",
    "Books & Literature",
    "Food & Cuisine",
    "Sports & Recreation",
    "Fitness & Wellness",
    "Mental Health",
    "Architecture & Design",
    "Real Estate",
    "Telecommunications",
    "Renewable Energy",
    "Space Exploration",
    "Wildlife & Nature",
    "Weather & Climate",
    "History & Heritage",
    "Politics & Governance",
    "NGOs & Nonprofits",
    "New York City",
    "London",
    "Tokyo",
    "Paris",
    "Berlin",
    "Singapore",
    "Dubai",
    "São Paulo",
    "Sydney",
    "Mumbai",
    "Madrid",
    "Lisbon",
    "Stockholm",
    "Amsterdam",
    "Seoul",
    "Japan",
    "France",
    "Germany",
    "Brazil",
    "India",
    "Italy",
    "Spain",
    "China",
    "United Kingdom",
    "Portugal",
    "Poetry",
]

SUBTOPICS = {
    "Poetry": [
        "Modernism",
        "Contemporary",
        "Modernism",
        "Haiku",
        "European Poetry",
        "Asian Poetry",
        "Theme identification",
    ],
    "Tech Innovation": [
        "Artificial Intelligence",
        "Quantum Computing",
        "Robotics",
        "5G/6G Networks",
        "Biotechnology",
        "Green Tech",
        "Edge Computing",
        "Cybersecurity",
    ],
    "Global Markets": [
        "Stock Exchanges",
        "Cryptocurrency",
        "International Trade",
        "Foreign Investment",
        "Commodity Markets",
        "Emerging Markets",
        "Foreign Exchange",
        "Market Regulations",
    ],
    "Environmental Policy": [
        "Carbon Trading",
        "Renewable Energy Initiatives",
        "Wildlife Protection",
        "Urban Planning",
        "Waste Management",
        "Climate Agreements",
        "Marine Conservation",
    ],
    "Public Health": [
        "Disease Prevention",
        "Healthcare Systems",
        "Vaccination Programs",
        "Mental Health Services",
        "Maternal Health",
        "Epidemiology",
        "Health Technology",
    ],
    "Urban Development": [
        "Smart Cities",
        "Public Transportation",
        "Housing Projects",
        "Green Spaces",
        "Infrastructure",
        "Urban Planning",
        "Sustainable Development",
    ],
    "International Relations": [
        "Diplomatic Missions",
        "Trade Agreements",
        "Cultural Exchange",
        "Peace Negotiations",
        "International Aid",
        "Global Security",
        "Regional Alliances",
    ],
    "Education Reform": [
        "Digital Learning",
        "Curriculum Changes",
        "Teacher Training",
        "Assessment Methods",
        "Special Education",
        "Higher Education",
        "STEM Initiatives",
    ],
    "Cultural Trends": [
        "Social Media Influence",
        "Fashion Movements",
        "Entertainment Trends",
        "Digital Culture",
        "Cultural Festivals",
        "Art Movements",
        "Pop Culture",
    ],
    "Scientific Discoveries": [
        "Space Exploration",
        "Medical Breakthroughs",
        "Physics Advances",
        "Genetic Research",
        "Archaeological Finds",
        "Marine Biology",
        "Climate Science",
    ],
    "Economic Policy": [
        "Monetary Policy",
        "Fiscal Measures",
        "Trade Regulations",
        "Tax Reform",
        "Employment Policy",
        "Banking Regulations",
        "Economic Stimulus",
    ],
    "Sports Industry": [
        "Professional Leagues",
        "Sports Technology",
        "Athletic Training",
        "Sports Medicine",
        "E-sports",
        "Sports Management",
        "Athletic Equipment",
    ],
    "Media & Entertainment": [
        "Streaming Services",
        "Film Production",
        "Gaming Industry",
        "Digital Media",
        "Publishing",
        "Broadcasting",
        "Content Creation",
    ],
    "Workplace Transformation": [
        "Remote Work",
        "Office Technology",
        "Employee Wellness",
        "Corporate Culture",
        "HR Innovation",
        "Workplace Safety",
        "Professional Development",
    ],
    "Transportation & Mobility": [
        "Electric Vehicles",
        "Autonomous Driving",
        "Public Transit",
        "Aviation",
        "Ride Sharing",
        "Maritime Transport",
        "Urban Mobility",
    ],
    "Food & Agriculture": [
        "Sustainable Farming",
        "Food Technology",
        "Organic Production",
        "Agricultural Policy",
        "Food Safety",
        "Urban Farming",
        "Agricultural Trade",
    ],
    "Medical & Healthcare": [
        "Telemedicine",
        "Medical Devices",
        "Pharmaceutical Research",
        "Healthcare IT",
        "Patient Care",
        "Medical Insurance",
        "Clinical Trials",
    ],
    "Legal & Compliance": [
        "Corporate Law",
        "Intellectual Property",
        "Data Protection",
        "Regulatory Compliance",
        "International Law",
        "Consumer Rights",
        "Legal Technology",
    ],
    "E-commerce & Retail": [
        "Online Marketplaces",
        "Digital Payment",
        "Retail Technology",
        "Supply Chain",
        "Customer Experience",
        "Mobile Commerce",
        "Retail Analytics",
    ],
    "Financial Services": [
        "Digital Banking",
        "Investment Management",
        "Insurance",
        "Payment Systems",
        "Wealth Management",
        "Risk Management",
        "Financial Technology",
    ],
    "Gaming & Software": [
        "Game Development",
        "Cloud Gaming",
        "Mobile Games",
        "Gaming Hardware",
        "Software Development",
        "Virtual Reality",
        "Gaming Communities",
    ],
    "Marketing & Advertising": [
        "Digital Marketing",
        "Brand Strategy",
        "Social Media Marketing",
        "Content Marketing",
        "Market Research",
        "Advertising Technology",
        "Campaign Management",
    ],
    "Government Documentation": [
        "Policy Documents",
        "Legal Records",
        "Public Notices",
        "Official Forms",
        "Legislative Documents",
        "Regulatory Guidelines",
        "Administrative Procedures",
    ],
    "Academic Research": [
        "Scientific Publications",
        "Research Methodology",
        "Peer Review",
        "Academic Collaboration",
        "Research Funding",
        "Data Analysis",
        "Research Ethics",
    ],
    "Patents & Intellectual Property": [
        "Patent Applications",
        "Trademark Registration",
        "Copyright Protection",
        "IP Litigation",
        "International Patents",
        "Trade Secrets",
        "IP Strategy",
    ],
    "Manufacturing & Safety": [
        "Quality Control",
        "Industrial Safety",
        "Production Processes",
        "Workplace Standards",
        "Equipment Safety",
        "Safety Regulations",
        "Risk Assessment",
    ],
    "Tourism & Hospitality": [
        "Hotel Management",
        "Travel Services",
        "Tourism Marketing",
        "Cultural Tourism",
        "Eco-Tourism",
        "Event Planning",
        "Customer Service",
    ],
    "Religious & Cultural Studies": [
        "Religious Traditions",
        "Cultural Heritage",
        "Interfaith Dialogue",
        "Religious Practices",
        "Cultural Anthropology",
        "Sacred Texts",
        "Religious Education",
    ],
    "Insurance & Risk Management": [
        "Insurance Products",
        "Risk Assessment",
        "Claims Processing",
        "Underwriting",
        "Insurance Technology",
        "Regulatory Compliance",
        "Risk Mitigation",
    ],
    "Consumer Electronics": [
        "Mobile Devices",
        "Smart Home",
        "Wearable Technology",
        "Audio Equipment",
        "Display Technology",
        "Gaming Hardware",
        "Personal Computing",
    ],
    "Pharmaceutical Industry": [
        "Drug Development",
        "Clinical Trials",
        "Regulatory Approval",
        "Manufacturing",
        "Research & Development",
        "Market Access",
        "Patient Safety",
    ],
    "Fashion & Apparel": [
        "Fashion Design",
        "Textile Industry",
        "Sustainable Fashion",
        "Retail Fashion",
        "Fashion Technology",
        "Luxury Brands",
        "Fashion Marketing",
    ],
    "Beauty & Cosmetics": [
        "Skincare",
        "Makeup Products",
        "Natural Cosmetics",
        "Beauty Technology",
        "Product Development",
        "Marketing",
        "Sustainability",
    ],
    "Home & Living": [
        "Interior Design",
        "Smart Home",
        "Furniture",
        "Home Improvement",
        "Sustainable Living",
        "Home Technology",
        "Decorative Arts",
    ],
    "Automotive Industry": [
        "Vehicle Manufacturing",
        "Electric Vehicles",
        "Autonomous Technology",
        "Auto Design",
        "Car Technology",
        "Safety Systems",
        "Market Trends",
    ],
    "Social Media": [
        "Platform Development",
        "Content Creation",
        "Social Analytics",
        "User Engagement",
        "Social Commerce",
        "Digital Communities",
        "Influencer Marketing",
    ],
    "Dating & Relationships": [
        "Online Dating",
        "Relationship Counseling",
        "Dating Apps",
        "Social Connection",
        "Relationship Psychology",
        "Dating Culture",
        "Personal Growth",
    ],
    "Parenting & Family": [
        "Child Development",
        "Family Health",
        "Education",
        "Family Dynamics",
        "Parenting Resources",
        "Child Safety",
        "Family Planning",
    ],
    "Arts & Culture": [
        "Visual Arts",
        "Performance Art",
        "Cultural Heritage",
        "Art Education",
        "Digital Art",
        "Cultural Events",
        "Art Market",
    ],
    "Music Industry": [
        "Music Production",
        "Digital Distribution",
        "Live Events",
        "Music Technology",
        "Artist Management",
        "Music Publishing",
        "Industry Trends",
    ],
    "Film & Cinema": [
        "Film Production",
        "Distribution",
        "Film Technology",
        "Cinema Innovation",
        "Film Industry",
        "Digital Effects",
        "Film Marketing",
    ],
    "Books & Literature": [
        "Publishing Industry",
        "Digital Publishing",
        "Literary Trends",
        "Book Marketing",
        "Author Platform",
        "Literary Events",
        "Reading Technology",
    ],
    "Food & Cuisine": [
        "Culinary Arts",
        "Food Culture",
        "Restaurant Industry",
        "Food Innovation",
        "Dietary Trends",
        "Food Technology",
        "Culinary Education",
    ],
    "Sports & Recreation": [
        "Professional Sports",
        "Recreational Activities",
        "Sports Technology",
        "Fitness Training",
        "Sports Medicine",
        "Equipment Innovation",
        "Sports Management",
    ],
    "Fitness & Wellness": [
        "Exercise Programs",
        "Wellness Technology",
        "Mental Health",
        "Nutrition",
        "Personal Training",
        "Wellness Education",
        "Health Tracking",
    ],
    "Mental Health": [
        "Therapy Services",
        "Mental Health Technology",
        "Support Programs",
        "Research & Treatment",
        "Workplace Mental Health",
        "Youth Mental Health",
        "Mental Health Education",
    ],
    "Architecture & Design": [
        "Urban Architecture",
        "Sustainable Design",
        "Interior Design",
        "Digital Architecture",
        "Design Innovation",
        "Building Technology",
        "Architectural Heritage",
    ],
    "Real Estate": [
        "Property Development",
        "Real Estate Technology",
        "Market Analysis",
        "Property Management",
        "Investment",
        "Commercial Real Estate",
        "Sustainable Building",
    ],
    "Telecommunications": [
        "Network Infrastructure",
        "Mobile Technology",
        "Communication Services",
        "Digital Networks",
        "Telecom Innovation",
        "Wireless Technology",
        "Industry Standards",
    ],
    "Renewable Energy": [
        "Solar Power",
        "Wind Energy",
        "Energy Storage",
        "Green Technology",
        "Energy Policy",
        "Sustainable Development",
        "Clean Energy Innovation",
    ],
    "Space Exploration": [
        "Space Technology",
        "Satellite Systems",
        "Space Research",
        "Space Industry",
        "Astronomical Discovery",
        "Space Travel",
        "Space Policy",
    ],
    "Wildlife & Nature": [
        "Conservation",
        "Biodiversity",
        "Wildlife Research",
        "Environmental Protection",
        "Natural Habitats",
        "Species Preservation",
        "Ecosystem Management",
    ],
    "Weather & Climate": [
        "Climate Science",
        "Weather Forecasting",
        "Climate Change",
        "Atmospheric Research",
        "Environmental Impact",
        "Climate Technology",
        "Weather Systems",
    ],
    "History & Heritage": [
        "Historical Research",
        "Cultural Preservation",
        "Archaeological Studies",
        "Heritage Conservation",
        "Historical Education",
        "Digital Archives",
        "Cultural Memory",
    ],
    "Politics & Governance": [
        "Political Systems",
        "Public Policy",
        "Government Innovation",
        "Electoral Processes",
        "Political Communication",
        "Civic Technology",
        "Governance Reform",
    ],
    "NGOs & Nonprofits": [
        "Social Impact",
        "Humanitarian Aid",
        "Nonprofit Management",
        "Fundraising",
        "Community Development",
        "International Development",
        "Social Innovation",
    ],
    "Math & Statistics": [
        "Mathematical Research",
        "Statistical Analysis",
        "Data Science",
        "Calculus",
        "Probability Theory",
        "Linear Algebra",
        "Math Education",
        "Derivatives",
        "Regression Analysis",
        "Bayesian Statistics",
        "Primitives",
    ],
    "Quantitative Finance": [
        "Financial Modeling",
        "Algorithmic Trading",
        "Risk Management",
        "Derivatives Pricing",
        "Portfolio Management",
        "Quantitative Analysis",
        "Financial Engineering",
        "Market Microstructure",
    ],
    "Artificial Intelligence": [
        "Machine Learning",
        "Deep Learning",
        "Neural Networks",
        "Computer Vision",
        "Natural Language Processing",
        "AI Ethics",
        "AI Applications",
        "AI Research",
    ],
    "Natural Language Processing": [
        "Text Analysis",
        "Speech Recognition",
        "Language Translation",
        "Sentiment Analysis",
        "Language Generation",
        "Language Understanding",
        "Language Processing",
        "Language Models",
    ],
    "Physics & Chemistry": [
        "Physical Sciences",
        "Chemical Research",
        "Quantum Physics",
        "Thermodynamics",
        "Particle Physics",
        "Organic Chemistry",
        "Physical Chemistry",
    ],
    "Biology & Genetics": [
        "Biological Research",
        "Genetic Engineering",
        "Cell Biology",
        "Evolutionary Biology",
        "Microbiology",
        "Molecular Genetics",
        "Biotechnology",
    ],
    "Computer Science": [
        "Software Development",
        "Computer Programming",
        "Algorithms",
        "Operating Systems",
        "Computer Networks",
        "Data Structures",
        "Computer Security",
    ],
    "New York City": [
        "Business & Finance",
        "Arts & Culture",
        "Food & Dining",
        "Urban Development",
        "Tourism",
        "Entertainment",
        "Sports Teams",
    ],
    "London": [
        "Financial Services",
        "Cultural Heritage",
        "Food Scene",
        "Theatre & Arts",
        "Royal Traditions",
        "Urban Transport",
        "Sports Culture",
    ],
    "Tokyo": [
        "Technology Industry",
        "Traditional Culture",
        "Cuisine",
        "Pop Culture",
        "Urban Innovation",
        "Fashion",
        "Entertainment Districts",
    ],
    "Paris": [
        "Fashion Industry",
        "Culinary Arts",
        "Cultural Landmarks",
        "Art Scene",
        "Tourism Industry",
        "Luxury Brands",
        "Urban Life",
    ],
    "Berlin": [
        "Startup Scene",
        "Cultural History",
        "Nightlife",
        "Art Community",
        "Tech Industry",
        "Urban Planning",
        "Alternative Culture",
    ],
    "Singapore": [
        "Financial Hub",
        "Food Culture",
        "Smart City Initiatives",
        "Cultural Diversity",
        "Business Innovation",
        "Urban Planning",
        "Education",
    ],
    "Dubai": [
        "Business Center",
        "Tourism Industry",
        "Luxury Lifestyle",
        "Urban Development",
        "International Trade",
        "Technology Innovation",
        "Cultural Traditions",
    ],
    "São Paulo": [
        "Business Hub",
        "Cultural Scene",
        "Food & Dining",
        "Urban Life",
        "Entertainment",
        "Fashion Industry",
        "Sports Culture",
    ],
    "Sydney": [
        "Lifestyle & Culture",
        "Business District",
        "Tourism",
        "Sports Events",
        "Entertainment",
        "Food Scene",
        "Urban Development",
    ],
    "Mumbai": [
        "Film Industry",
        "Business Center",
        "Cultural Heritage",
        "Food Culture",
        "Urban Development",
        "Entertainment",
        "Fashion",
    ],
    "Madrid": [
        "Cultural Heritage",
        "Food & Wine",
        "Sports Culture",
        "Arts Scene",
        "Business Hub",
        "Urban Life",
        "Tourism",
    ],
    "Lisbon": [
        "Startup Ecosystem",
        "Cultural History",
        "Food & Wine",
        "Tourism Industry",
        "Urban Innovation",
        "Maritime Heritage",
        "Arts Scene",
    ],
    "Stockholm": [
        "Tech Innovation",
        "Design Culture",
        "Sustainability",
        "Urban Planning",
        "Business Hub",
        "Cultural Scene",
        "Food & Lifestyle",
    ],
    "Amsterdam": [
        "Cultural Heritage",
        "Urban Planning",
        "Business Innovation",
        "Art Scene",
        "Cycling Culture",
        "Tourism",
        "Tech Industry",
    ],
    "Seoul": [
        "Tech Industry",
        "Pop Culture",
        "Food Scene",
        "Fashion Trends",
        "Urban Innovation",
        "Entertainment",
        "Business Hub",
    ],
    "Japan": [
        "Traditional Culture",
        "Technology Industry",
        "Popular Culture",
        "Business Practices",
        "Food & Cuisine",
        "Arts & Crafts",
        "Social Customs",
    ],
    "France": [
        "Culinary Arts",
        "Fashion Industry",
        "Cultural Heritage",
        "Wine Industry",
        "Tourism",
        "Business Culture",
        "Arts & Literature",
    ],
    "Germany": [
        "Automotive Industry",
        "Business Innovation",
        "Cultural Traditions",
        "Sports Culture",
        "Technology Sector",
        "Education System",
        "Urban Development",
    ],
    "Brazil": [
        "Cultural Festivals",
        "Sports Culture",
        "Business Environment",
        "Food & Cuisine",
        "Music Scene",
        "Tourism Industry",
        "Urban Life",
    ],
    "India": [
        "Technology Sector",
        "Cultural Diversity",
        "Film Industry",
        "Culinary Traditions",
        "Business Hub",
        "Traditional Arts",
        "Festival Culture",
    ],
    "Italy": [
        "Food & Wine",
        "Fashion Industry",
        "Cultural Heritage",
        "Tourism Sector",
        "Design Industry",
        "Business Culture",
        "Arts Scene",
    ],
    "Spain": [
        "Cultural Traditions",
        "Culinary Arts",
        "Tourism Industry",
        "Sports Culture",
        "Business Environment",
        "Arts & Entertainment",
        "Urban Life",
    ],
    "China": [
        "Technology Industry",
        "Business Culture",
        "Traditional Customs",
        "Urban Development",
        "Cultural Heritage",
        "Food Culture",
        "Innovation Hub",
    ],
    "United Kingdom": [
        "Financial Services",
        "Cultural Heritage",
        "Education System",
        "Business Innovation",
        "Arts & Entertainment",
        "Sports Culture",
        "Urban Life",
    ],
    "Portugal": [
        "Tourism Industry",
        "Food & Wine",
        "Cultural Heritage",
        "Business Innovation",
        "Maritime Culture",
        "Urban Development",
        "Arts Scene",
    ],
    "Newspapers and Magazines": [
        "Financial Times",
        "The Economist",
        "The New York Times",
        "The Guardian",
        "The Wall Street Journal",
        "The Times",
        "The Washington Post",
        "The Atlantic",
    ],
    "Journalists and Writers": [
        "Ezra Klein",
        "Maggie Haberman",
        "David Brooks",
        "Kara Swisher",
        "Andrew Ross Sorkin",
        "Maureen Dowd",
        "David Leonhardt",
        "Nate Silver",
        "Ben Smith",
    ],
}

STYLES = [
    "creative",
    "concise",
    "technical",
    "formal",
    "informal",
    "narrative",
    "persuasive",
    "descriptive",
    "analytical",
    "humorous",
    "poetic",
    "casual",
    "academic",
    "journalistic",
    "neutral",
    "elaborate",
    "minimalist",
    "rushed",
]

AUDIENCES = [
    "children",
    "teenagers",
    "young adults",
    "parents",
    "seniors",
    "professionals",
    "college students",
    "educators",
    "general public",
    "beginners",
    "experts",
    "middle-aged adults",
]

LENGTHS = ["short", "medium", "long", "very long"]

DIFFICULTIES = ["easy", "medium", "hard", "very hard", "arguably impossible to answer"]

WRITING_PROFICIENCIES = ["low", "medium", "high", "virtuoso"]

TRANSLATION_HARD_RULES = [
    "Write dates in DD/MM/YYYY format",
    "Convert measurements from imperial to metric (e.g., miles to kilometers)",
    "Convert temperatures from Fahrenheit to Celsius",
    "Use 24-hour time format instead of AM/PM",
    "Maintain proper nouns exactly as written in the source text",
    "Convert currency amounts with specified exchange rates",
    "Use specified regional spelling variants (e.g., British vs. American English)",
    "Place quotation marks according to target language conventions (" " vs. « »)",
    "Format phone numbers according to target country conventions",
    "Use decimal comma instead of decimal point where applicable",
    "Maintain specific formatting for legal/official document numbers",
    "Convert time zones to target region's time zone",
    "Use specified abbreviations for titles (Dr., Mr., Prof., etc.)",
    "Format addresses according to target country conventions",
    "Maintain HTML/markup tags in exact positions",
    "Convert units of weight (pounds to kilograms)",
    "Use specified capitalization rules for titles and headings",
    "Maintain specific character count limits",
    "Format numbers according to local conventions (e.g., 1,000 vs 1.000)",
]
